steps:
  # Debug step to show environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-info'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "=== DEBUG INFORMATION ==="
        echo "Build ID: $BUILD_ID"
        echo "Project ID: $PROJECT_ID"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Branch: $BRANCH_NAME"
        echo "Repository: $REPO_NAME"
        echo "Trigger Name: $TRIGGER_NAME"
        echo "=========================="

        echo "All Environment Variables:"
        env | sort

        echo "Git Information:"
        git log -1 || echo "Cannot access git information"

  # Publish event to Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'publish-to-pubsub'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Creating JSON payload..."

        JSON_PAYLOAD=$(printf '{
          "repository": {
            "name": "%s",
            "full_name": "%s/%s"
          },
          "ref": "refs/heads/%s",
          "pusher": {
            "name": "Cloud Build",
            "email": "cloud-build@example.com"
          },
          "commits": [{
            "id": "%s",
            "message": "Triggered by Cloud Build - %s",
            "author": {
              "name": "Cloud Build",
              "email": "cloud-build@example.com"
            }
          }]
        }' "$REPO_NAME" "$PROJECT_ID" "$REPO_NAME" "$BRANCH_NAME" "$COMMIT_SHA" "$BUILD_ID")

        echo "Final JSON payload:"
        echo "$JSON_PAYLOAD"

        echo "Publishing to Pub/Sub topic: github-events"
        gcloud pubsub topics publish github-events \
          --message="$JSON_PAYLOAD" \
          --project="${PROJECT_ID}"

        echo "Listing subscriptions for topic:"
        gcloud pubsub topics list-subscriptions github-events \
          --project="${PROJECT_ID}" || echo "No subscriptions found or insufficient permissions"

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TOPIC_NAME=github-events'

timeout: '600s'

