steps:
  # Debug environment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-info'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "=== DEBUG INFORMATION ==="
        echo "Build ID: $BUILD_ID"
        echo "Project ID: $PROJECT_ID"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Branch: $BRANCH_NAME"
        echo "Repository: $REPO_NAME"
        echo "Trigger Name: $TRIGGER_NAME"
        echo "=========================="

        echo "All Environment Variables:"
        env | sort

        echo "Git Information:"
        git log -1 || echo "Cannot access git information"

  # Create JSON payload and publish to Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'publish-to-pubsub'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Creating event.json file..."
        cat <<EOF > /workspace/event.json
{
  "repository": {
    "name": "${REPO_NAME:-unknown}",
    "full_name": "${PROJECT_ID:-unknown}/${REPO_NAME:-unknown}"
  },
  "ref": "refs/heads/${BRANCH_NAME:-unknown}",
  "pusher": {
    "name": "Cloud Build",
    "email": "cloud-build@example.com"
  },
  "commits": [{
    "id": "${COMMIT_SHA:-unknown}",
    "message": "Triggered by Cloud Build - ${BUILD_ID:-unknown}",
    "author": {
      "name": "Cloud Build",
      "email": "cloud-build@example.com"
    }
  }]
}
EOF

        echo "Compacting JSON with jq..."
        COMPACT_JSON=$(jq -c . /workspace/event.json)

        echo "Publishing message to Pub/Sub..."
        gcloud pubsub topics publish github-events \
          --message="$COMPACT_JSON" \
          --project="$PROJECT_ID"

        echo "Published message successfully."

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TOPIC_NAME=github-events'

timeout: '600s'


