steps:
  # Debug step to show environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== DEBUG INFORMATION ==="
        echo "Build ID: $BUILD_ID"
        echo "Project ID: $PROJECT_ID"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Branch: $BRANCH_NAME"
        echo "Repository: $REPO_NAME"
        echo "Trigger Name: $TRIGGER_NAME"
        echo "=========================="

        echo "\nAll Environment Variables:"
        env | sort

        echo "\nGit Information:"
        git log -1 || echo "Cannot access git information"

  # Publish event to Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'publish-to-pubsub'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating JSON payload..."
        JSON_PAYLOAD=$(cat <<EOF
{
  "repository": {
    "name": "${REPO_NAME:-unknown}",
    "full_name": "${PROJECT_ID:-unknown}/${REPO_NAME:-unknown}"
  },
  "ref": "refs/heads/${BRANCH_NAME:-unknown}",
  "pusher": {
    "name": "Cloud Build",
    "email": "cloud-build@example.com"
  },
  "commits": [{
    "id": "${COMMIT_SHA:-unknown}",
    "message": "Triggered by Cloud Build - ${BUILD_ID:-unknown}",
    "author": {
      "name": "Cloud Build",
      "email": "cloud-build@example.com"
    }
  }]
}
EOF
)

        echo "Final JSON payload:"
        echo "$JSON_PAYLOAD"

        echo "\nPublishing to Pub/Sub topic: github-events"
        gcloud pubsub topics publish github-events \
          --message="$JSON_PAYLOAD" \
          --project="${PROJECT_ID}"

        echo "\nListing subscriptions for topic:"
        gcloud pubsub topics list-subscriptions github-events \
          --project="${PROJECT_ID}" || echo "No subscriptions found or insufficient permissions"

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TOPIC_NAME=github-events'

timeout: '600s'
